#####################################################################
# Site/blog specific settings
#####################################################################

# Blog Information
title:                "Site title"
tagline:              "subtitle"
description:          "site description"
short_name:           "Company Name"
baseurl:              /
url:                  http://example.com/
author:
  name:               "Ara Abcarians"
  email:              "hello@itsmeara.com"

twitter:              itsmeara
github:               itsmeara
gplus:                '101183822199340201470'

# Sharing settings
sharing:
  twitter:            true
  facebook:           true
  gplus:              true
  hn:                 false

# Analytics     
analytics:
  google: 
    # eg. 'UA-123-12'
    site_id:               'UA-123-12'

# Google Fonts
# eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
google_font:          "Droid+Sans:400,700"




#####################################################################
# General jekyll settings
#####################################################################

source:               .
destination:          ./_build
plugins:              ./_plugins
layouts:              ./_layouts
include:              ['.htaccess']
# exclude:              []
keep_files:           ['.git','.svn']
pygments:             true
markdown:             rdiscount
permalink:            pretty
# paginate_path:        'page:num'
paginate:             5
excerpt_separator:    "<!-- more -->"
