name: Your New Jekyll Site

source:      .
destination: ./_build
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
timezone:    nil
encoding:    nil

future:      true
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink: /:year/:month/:day/:title
paginate: 10
paginate_path: 'page:num'


markdown: redcarpet
# markdown:      maruku
# markdown_ext:  markdown,mkd,mkdn,md
# textile_ext:   textile

excerpt_separator: "\n\n"